In [ ]:
#Numpy - Powerful python library for numerical calculations over n-dimensional data
#Pandas , Matplotlib
a = 5
b = 2
print(a/5)

1.0


In [ ]:
l = [5,8,9,4,3]
l*2

[5, 8, 9, 4, 3, 5, 8, 9, 4, 3]

In [ ]:
import numpy as np

In [ ]:
#numpy functions - array()
n = np.array([5,8,9,4,3])

In [ ]:
print(type(l))
print(type(n))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(l*2)
print(n*2)

[5, 8, 9, 4, 3, 5, 8, 9, 4, 3]
[10 16 18  8  6]


In [ ]:
l1 = [[3,4,5,6,7],[21,43,54,65,76]]
n1 = np.array([[3,4,5,6,7],[21,43,54,65,76]])

In [ ]:
print(l1)

[[3, 4, 5, 6, 7], [21, 43, 54, 65, 76]]


In [ ]:
print(n1)

[[ 3  4  5  6  7]
 [21 43 54 65 76]]


In [ ]:
#numpy functions - prod(),sum(),max(),min(),mean(),std(),argmax(),argmin()
print(n1.prod())
print(n1.sum())
print(n1.max())
print(n1.min())
print(n1.mean())
print(n1.argmax())
print(n1.argmin())

607028385600
284
76
3
28.4
9
0


In [ ]:
print(np.prod(n1))
print(np.sum(n1))
print(np.max(n1))
print(np.min(n1))
print(np.mean(n1))
print(np.argmax(n1))
print(np.argmin(n1))

607028385600
284
76
3
28.4
9
0


In [ ]:
#array[row index,column index]
print(n1[0,0]) #first row first value
print(n1[0,1]) #first row second value
print(n1[1,0]) #second row first value
print(n1[1,1]) #second row second value

3
4
21
43


In [ ]:
print(n.ndim)
print(n.size)
print(n.shape)

1
5
(5,)


In [ ]:
#dimension,size,shape - ndim,size,shape
print(n1.ndim)
print(n1.size)
print(n1.shape)

2
10
(2, 5)


In [ ]:
#Slicing in a numpy array
n2 = np.array([[2,3,4,5,6],[4,3,2,6,7],[1,2,4,5,6]])
print(n2)

[[2 3 4 5 6]
 [4 3 2 6 7]
 [1 2 4 5 6]]


In [ ]:
n2[1:3,1:3]

array([[3, 2],
       [2, 4]])

In [ ]:
n2[:,2:4]

array([[4, 5],
       [2, 6],
       [4, 5]])

In [ ]:
X = n2[:,0:4]
Y = n2[:,4:5]

In [ ]:
X

array([[2, 3, 4, 5],
       [4, 3, 2, 6],
       [1, 2, 4, 5]])

In [ ]:
Y

array([[6],
       [7],
       [6]])

In [ ]:
X[0,0]=246
print(X)

[[246   3   4   5]
 [  4   3   2   6]
 [  1   2   4   5]]


In [ ]:
n2

array([[246,   3,   4,   5,   6],
       [  4,   3,   2,   6,   7],
       [  1,   2,   4,   5,   6]])

In [ ]:
import copy
x1 = copy.deepcopy(n2[:,0:4])
y1 = copy.deepcopy(n2[:,4:5])

In [ ]:
x1[0,0]=22

In [ ]:
x1

array([[22,  3,  4,  5],
       [ 4,  3,  2,  6],
       [ 1,  2,  4,  5]])

In [ ]:
n2

array([[246,   3,   4,   5,   6],
       [  4,   3,   2,   6,   7],
       [  1,   2,   4,   5,   6]])

In [ ]:
#contacting
#vertical stack and horizontal stack
x1 = np.array([[3,4,5,6,7],[11,22,33,44,55],[21,32,43,54,65]])
x2 = np.array([[8,9,7,6,0],[1,4,5,6,7]])

In [ ]:
x1

array([[ 3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55],
       [21, 32, 43, 54, 65]])

In [ ]:
x2

array([[8, 9, 7, 6, 0],
       [1, 4, 5, 6, 7]])

In [ ]:
#vstack,hstack
X1 = np.vstack((x1,x2))
X1

array([[ 3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55],
       [21, 32, 43, 54, 65],
       [ 8,  9,  7,  6,  0],
       [ 1,  4,  5,  6,  7]])

In [ ]:
x3 = np.array([[2,3],[3,5],[2,1]])
x3

array([[2, 3],
       [3, 5],
       [2, 1]])

In [ ]:
X2 = np.hstack((x1,x3))
X2

array([[ 3,  4,  5,  6,  7,  2,  3],
       [11, 22, 33, 44, 55,  3,  5],
       [21, 32, 43, 54, 65,  2,  1]])

In [ ]:
#shape manipulation - reshape,transpose
n2

array([[246,   3,   4,   5,   6],
       [  4,   3,   2,   6,   7],
       [  1,   2,   4,   5,   6]])

In [ ]:
n2.reshape(5,3)

array([[246,   3,   4],
       [  5,   6,   4],
       [  3,   2,   6],
       [  7,   1,   2],
       [  4,   5,   6]])

In [ ]:
np.transpose(n2)

array([[246,   4,   1],
       [  3,   3,   2],
       [  4,   2,   4],
       [  5,   6,   5],
       [  6,   7,   6]])

In [ ]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(3, 5)
(2, 5)
(3, 2)


In [ ]:
np.dot(x1,np.transpose(x2))

array([[ 131,  129],
       [ 781,  913],
       [1081, 1143]])

In [ ]:
np.dot(np.transpose(x1),x3)

array([[ 81,  85],
       [138, 154],
       [195, 223],
       [252, 292],
       [309, 361]])

In [ ]:
np.dot(x3,x2)

array([[19, 30, 29, 30, 21],
       [29, 47, 46, 48, 35],
       [17, 22, 19, 18,  7]])

In [ ]:
n3 = np.arange(0,36).reshape(3,4,3)
n3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
n3[1:2,1:3,1:3]

array([[[16, 17],
        [19, 20]]])

In [ ]:
k1 = np.zeros([3,4])
k2 = np.ones([2,5])
k3 = np.eye(5)

In [ ]:
k1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
k2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
k3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Pandas
z = k3.copy()
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
s = np.array([3,6,7,8,9])
s[1:4]

array([6, 7, 8])

In [ ]:
#Images - RGB
k1 = np.arange(0,36).reshape(3,4,3)
k1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
k1[2:3,3:4,:]

array([[[33, 34, 35]]])

In [ ]:
k1[1:2,1:3,1:3]

array([[[16, 17],
        [19, 20]]])

In [ ]:
k1[1:2,:,2:3]

array([[[14],
        [17],
        [20],
        [23]]])

In [ ]:
#Pandas - Used to access, analyse or manipulate the data file 
#dataframe
import pandas as pd
p = pd.DataFrame({'a':[2,4,5,6,7] , 'b':[12,34,13,54,66] , 'c':['2','3','5','1','9'],
                  'd': ['22C','24C','43C','55C','11C']})

In [ ]:
p

a   b  c    d
0  2  12  2  22C
1  4  34  3  24C
2  5  13  5  43C
3  6  54  1  55C
4  7  66  9  11C

In [ ]:
#dtypes - to know datatype of a dataframe
#astype() - to change datatype in a dataframe
p.dtypes

a     int64
b     int64
c    object
d    object
dtype: object

In [ ]:
p['a']

0    2
1    4
2    5
3    6
4    7
Name: a, dtype: int64

In [ ]:
print(p['a'].max())
print(p['a'].mean())

7
4.8


In [ ]:
p['b'].min()

12

In [ ]:
p['c'] = p['c'].astype(float)

In [ ]:
p['c'].mean()

4.0

In [ ]:
p['c'].sum()

20.0

In [ ]:
'2'+'3'+'5'+'1'+'9'

'23519'

In [ ]:
#.str.replace()- used to replace any existing string value in a data series
p['d'] = p['d'].str.replace('C','').astype(int)

In [ ]:
p

a   b    c   d
0  2  12  2.0  22
1  4  34  3.0  24
2  5  13  5.0  43
3  6  54  1.0  55
4  7  66  9.0  11

In [ ]:
p['d'].mean()

31.0

In [ ]:
#creating dataframe
#Checking the data types of a dataframe
#Manipulating the data types of a data series in a dataframe
#replace any string value in a data series

In [ ]:
p[['a','b','d']]

a   b   d
0  2  12  22
1  4  34  24
2  5  13  43
3  6  54  55
4  7  66  11

In [ ]:
#loc
p.loc[0:3,'a':'c']

a   b    c
0  2  12  2.0
1  4  34  3.0
2  5  13  5.0
3  6  54  1.0

In [ ]:
p.loc[0:3,['a','d']]

a   d
0  2  22
1  4  24
2  5  43
3  6  55

In [ ]:
#range - in terms of index
#iloc
p.iloc[0:4,0:-1]

a   b    c
0  2  12  2.0
1  4  34  3.0
2  5  13  5.0
3  6  54  1.0

In [ ]:
p.iloc[:,-1:]

d
0  22
1  24
2  43
3  55
4  11

In [ ]:
ship = pd.read_csv('http://bit.ly/kaggletrain')
ship.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
ship.shape

(891, 12)

In [ ]:
ship.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
#remove a column - drop()

In [ ]:
ship = ship.drop(['Fare','Ticket'],axis=1)

In [ ]:
ship.head(10)

PassengerId  Survived  Pclass  ... Parch Cabin  Embarked
0            1         0       3  ...     0   NaN         S
1            2         1       1  ...     0   C85         C
2            3         1       3  ...     0   NaN         S
3            4         1       1  ...     0  C123         S
4            5         0       3  ...     0   NaN         S
5            6         0       3  ...     0   NaN         Q
6            7         0       1  ...     0   E46         S
7            8         0       3  ...     1   NaN         S
8            9         1       3  ...     2   NaN         S
9           10         1       2  ...     0   NaN         C

[10 rows x 10 columns]

In [ ]:
ship = ship.drop([2,4],axis=0)

In [ ]:
ship.head()

PassengerId  Survived  Pclass  ... Parch Cabin  Embarked
0            1         0       3  ...     0   NaN         S
1            2         1       1  ...     0   C85         C
3            4         1       1  ...     0  C123         S
5            6         0       3  ...     0   NaN         Q
6            7         0       1  ...     0   E46         S

[5 rows x 10 columns]

In [ ]:
ship.drop(ship.index[4:7],axis=0)

PassengerId  Survived  Pclass  ... Parch Cabin  Embarked
0              1         0       3  ...     0   NaN         S
1              2         1       1  ...     0   C85         C
3              4         1       1  ...     0  C123         S
5              6         0       3  ...     0   NaN         Q
9             10         1       2  ...     0   NaN         C
..           ...       ...     ...  ...   ...   ...       ...
886          887         0       2  ...     0   NaN         S
887          888         1       1  ...     0   B42         S
888          889         0       3  ...     2   NaN         S
889          890         1       1  ...     0  C148         C
890          891         0       3  ...     0   NaN         Q

[886 rows x 10 columns]

In [ ]:
ship.drop(ship.columns[2:5],axis=1)

PassengerId  Survived   Age  SibSp  Parch Cabin Embarked
0              1         0  22.0      1      0   NaN        S
1              2         1  38.0      1      0   C85        C
3              4         1  35.0      1      0  C123        S
5              6         0   NaN      0      0   NaN        Q
6              7         0  54.0      0      0   E46        S
..           ...       ...   ...    ...    ...   ...      ...
886          887         0  27.0      0      0   NaN        S
887          888         1  19.0      0      0   B42        S
888          889         0   NaN      1      2   NaN        S
889          890         1  26.0      0      0  C148        C
890          891         0  32.0      0      0   NaN        Q

[889 rows x 7 columns]

In [ ]:
ship.columns[2:5]

Index(['Pclass', 'Name', 'Sex'], dtype='object')

In [ ]:
ship.loc[3]['Name']

'Futrelle, Mrs. Jacques Heath (Lily May Peel)'

In [ ]:
#array+range = arange